name: Test and Lint

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        - name: Lint with Ruff
          run: |
            poetry run pip install ruff
            poetry run ruff --format=github --target-version=py37 .
          continue-on-error: true
        
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version: ["3.7", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pip install pytest pytest-cov
        poetry run python -m pytest tests/ --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=safegrid --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: |
          junit/test-results-${{ matrix.python-version }}.xml
          coverage.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}